apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd
  labels:
    app: httpd
spec:
  containers:
    - name: cntr-httpd
      image: httpd:latest
      resources:
        limits:
          cpu: "500m"
        requests:
          cpu: "200m"
      ports:
        - containerPort: 80
