apiVersion: metrics.wingsofovnia.github.com/v1alpha1
kind: MetricWebhook
metadata:
  name: gorand-metricwebhook
spec:
  selector:
    matchLabels:
      run: gorand
  webhook:
    port: 4030
    path: /metrics-webhook
  scrapeInterval: 30s
  cooldownAlert: true
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
