kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-webhook
subjects:
  - kind: ServiceAccount
    name: metrics-webhook
roleRef:
  kind: Role
  name: metrics-webhook
  apiGroup: rbac.authorization.k8s.io
