apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: golorem-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golorem
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 90
